name: anacostia

services:
  setup:
    image: python:3.12.4-slim
    volumes:
      - type: bind
        source: ./distributed_tests/testing_artifacts
        target: /testing_artifacts
      - type: bind
        source: ./distributed_tests/root-service
        target: /root-service
      - type: bind
        source: ./distributed_tests/leaf-service
        target: /leaf-service
      - type: bind
        source: ./distributed_tests/utils
        target: /utils
    command: python3 /utils/setup.py

  root-pipeline:
    build: .
    container_name: root-container
    volumes:
      - type: bind
        source: ./distributed_tests/root-service/service
        target: /service
      - type: bind
        source: ./distributed_tests/root-service/input_artifacts
        target: /input_artifacts
      - type: bind
        source: ./distributed_tests/leaf-service/output_artifacts
        target: /output_artifacts
      - type: bind
        source: ./distributed_tests/testing_artifacts
        target: /testing_artifacts
    ports:
      - "8000:8000"
    networks:
      - anacostia-network
    depends_on:
      setup:
        condition: service_completed_successfully

  leaf-pipeline:
    build: .
    container_name: leaf-container
    volumes:
      - type: bind
        source: ./distributed_tests/leaf-service/service
        target: /service
      - type: bind
        source: ./distributed_tests/leaf-service/input_artifacts
        target: /input_artifacts
      - type: bind
        source: ./distributed_tests/leaf-service/output_artifacts
        target: /output_artifacts
      - type: bind
        source: ./distributed_tests/testing_artifacts
        target: /testing_artifacts
    ports:
      - "8080:8080"
    networks:
      - anacostia-network
    depends_on:
      setup:
        condition: service_completed_successfully

networks:
  anacostia-network:
    driver: bridge
